#!/usr/bin/env bash
# Idempotently writes the /magento:init outputs into a project.
# Usage: apply-init.sh --block <file> --rules <file> [--root <dir>]
set -euo pipefail

block=""; rules=""; root="."
while [ $# -gt 0 ]; do
  case "$1" in
    --block) block="${2:-}"; shift 2 || break ;;
    --rules) rules="${2:-}"; shift 2 || break ;;
    --root)  root="${2:-}";  shift 2 || break ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done
if [ -z "$block" ] || [ -z "$rules" ] || [ ! -f "$block" ] || [ ! -f "$rules" ]; then
  echo "usage: apply-init.sh --block <file> --rules <file> [--root <dir>]" >&2
  exit 1
fi
cd "$root"

BEGIN='<!-- magento:begin -->'
END='<!-- magento:end -->'

has_live_block() { # true iff CLAUDE.md has both markers as whole lines OUTSIDE any fence, END after BEGIN
  awk -v b="$BEGIN" -v e="$END" '
    /^```/ { fence = !fence; next }
    !fence && $0 == b { sb = 1 }
    !fence && $0 == e && sb { se = 1 }
    END { exit (sb && se) ? 0 : 1 }
  ' CLAUDE.md
}

# --- CLAUDE.md ---
if [ ! -f CLAUDE.md ]; then
  if cat "$block" > CLAUDE.md; then
    echo "CLAUDE.md: created"
  else
    echo "CLAUDE.md: create failed" >&2
    exit 1
  fi
elif has_live_block; then
  # Marker lines must match the WHOLE line (not just a prefix) and are only
  # "live" outside a fenced code block (``` ... ```), so an illustrative
  # example of the markers inside a fence is never mistaken for the real one.
  # has_live_block above uses the identical fence-aware rule to decide whether
  # this (update) branch or the append branch below applies.
  if awk -v blockfile="$block" -v b="$BEGIN" -v e="$END" '
    BEGIN { fence = 0; skipping = 0 }
    {
      if ($0 ~ /^```/) { fence = !fence }
      else if (!fence) {
        if (!skipping && $0 == b) { while ((getline line < blockfile) > 0) print line; skipping = 1; next }
        if (skipping && $0 == e) { skipping = 0; next }
      }
      if (!skipping) print
    }
  ' CLAUDE.md > CLAUDE.md.tmp && mv CLAUDE.md.tmp CLAUDE.md; then
    echo "CLAUDE.md: updated"
  else
    rm -f CLAUDE.md.tmp
    echo "CLAUDE.md: update failed" >&2
    exit 1
  fi
else
  if { printf '\n'; cat "$block"; } >> CLAUDE.md; then
    echo "CLAUDE.md: appended"
  else
    echo "CLAUDE.md: append failed" >&2
    exit 1
  fi
fi

# --- .claude/rules/magento.md ---
mkdir -p .claude/rules
target=.claude/rules/magento.md
if [ ! -f "$target" ]; then
  cat "$rules" > "$target"; echo "$target: created"
elif head -1 "$target" | grep -q '^<!-- generated by the magento plugin'; then
  cat "$rules" > "$target"; echo "$target: updated"
else
  echo "$target: left alone (owned by you)"
fi
