#!/usr/bin/env bash
# Idempotently writes the /magento:init outputs into a project.
# Usage: apply-init.sh --block <file> --rules <file> [--root <dir>]
set -euo pipefail

block=""; rules=""; root="."
while [ $# -gt 0 ]; do
  case "$1" in
    --block) block="$2"; shift 2 ;;
    --rules) rules="$2"; shift 2 ;;
    --root)  root="$2";  shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done
if [ -z "$block" ] || [ -z "$rules" ] || [ ! -f "$block" ] || [ ! -f "$rules" ]; then
  echo "usage: apply-init.sh --block <file> --rules <file> [--root <dir>]" >&2
  exit 1
fi
cd "$root"

BEGIN='<!-- magento:begin -->'
END='<!-- magento:end -->'

# --- CLAUDE.md ---
if [ ! -f CLAUDE.md ]; then
  cat "$block" > CLAUDE.md
  echo "CLAUDE.md: created"
elif grep -qF "$BEGIN" CLAUDE.md && grep -qF "$END" CLAUDE.md; then
  awk -v blockfile="$block" -v b="$BEGIN" -v e="$END" '
    index($0, b) == 1 { while ((getline line < blockfile) > 0) print line; skipping = 1; next }
    index($0, e) == 1 { skipping = 0; next }
    !skipping { print }
  ' CLAUDE.md > CLAUDE.md.tmp && mv CLAUDE.md.tmp CLAUDE.md
  echo "CLAUDE.md: updated"
else
  { printf '\n'; cat "$block"; } >> CLAUDE.md
  echo "CLAUDE.md: appended"
fi

# --- .claude/rules/magento.md ---
mkdir -p .claude/rules
target=.claude/rules/magento.md
if [ ! -f "$target" ]; then
  cat "$rules" > "$target"; echo "$target: created"
elif head -1 "$target" | grep -q '^<!-- generated by the magento plugin'; then
  cat "$rules" > "$target"; echo "$target: updated"
else
  echo "$target: left alone (owned by you)"
fi
