#!/usr/bin/env bash
# Renders .claude/rules/magento.md from the conventions skill.
# Usage: render-rules.sh --version <v> [--hyva true|false] [--luma true|false]
set -euo pipefail
version=""; hyva="true"; luma="true"
while [ $# -gt 0 ]; do
  case "$1" in
    --version) version="$2"; shift 2 ;;
    --hyva)    hyva="$2";    shift 2 ;;
    --luma)    luma="$2";    shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done
if [ -z "$version" ]; then
  echo "usage: render-rules.sh --version <v> [--hyva true|false] [--luma true|false]" >&2
  exit 1
fi
src="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/skills/conventions/SKILL.md"

printf '<!-- generated by the magento plugin v%s — remove this line to take ownership; init will then leave this file alone -->\n' "$version"
awk -v hyva="$hyva" -v luma="$luma" '
  NR == 1 && $0 == "---" { infm = 1; next }
  infm { if ($0 == "---") infm = 0; next }
  /^## / {
    skip = 0
    if ($0 ~ /^## Frontend/ && $0 ~ /Hyv/ && hyva != "true") skip = 1
    if ($0 ~ /^## Frontend/ && $0 ~ /Luma/ && luma != "true") skip = 1
    if ($0 ~ /^## How this file is used/) skip = 1
  }
  !skip { print }
' "$src"
