#!/usr/bin/env bash
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
S="$ROOT/plugins/magento/scripts/apply-init.sh"
tmp=$(mktemp -d)
printf '<!-- magento:begin -->\n## Magento (v1)\n- edition: open-source\n<!-- magento:end -->\n' > "$tmp/block1"
printf '<!-- magento:begin -->\n## Magento (v2)\n- edition: commerce\n<!-- magento:end -->\n' > "$tmp/block2"
printf '<!-- generated by the magento plugin v0.1.0 — remove this line to take ownership; init will then leave this file alone -->\n# Rules v1\n' > "$tmp/rules1"
printf '<!-- generated by the magento plugin v0.1.0 — remove this line to take ownership; init will then leave this file alone -->\n# Rules v2\n' > "$tmp/rules2"

# A. fresh project: creates both
mkdir "$tmp/a"
bash "$S" --block "$tmp/block1" --rules "$tmp/rules1" --root "$tmp/a" > "$tmp/a.out"
assert_contains "$tmp/a.out" "^CLAUDE.md: created$" "A claude created"
assert_contains "$tmp/a.out" "^.claude/rules/magento.md: created$" "A rules created"
assert_eq "$(grep -c 'magento:begin' "$tmp/a/CLAUDE.md")" "1" "A one begin marker"
assert_contains "$tmp/a/.claude/rules/magento.md" "Rules v1" "A rules content"

# B. existing CLAUDE.md without markers: appends, keeps existing text
mkdir "$tmp/b"; printf '# My project\n\nKeep me.\n' > "$tmp/b/CLAUDE.md"
bash "$S" --block "$tmp/block1" --rules "$tmp/rules1" --root "$tmp/b" > "$tmp/b.out"
assert_contains "$tmp/b.out" "^CLAUDE.md: appended$" "B appended"
assert_contains "$tmp/b/CLAUDE.md" "^Keep me.$" "B kept text"
assert_eq "$(head -1 "$tmp/b/CLAUDE.md")" "# My project" "B original first line intact"
assert_eq "$(grep -c 'magento:begin' "$tmp/b/CLAUDE.md")" "1" "B one begin marker"

# C. run again with a new block: replaces, still one block, text after block preserved
printf '\nTrailing note.\n' >> "$tmp/b/CLAUDE.md"
bash "$S" --block "$tmp/block2" --rules "$tmp/rules2" --root "$tmp/b" > "$tmp/c.out"
assert_contains "$tmp/c.out" "^CLAUDE.md: updated$" "C updated"
assert_eq "$(grep -c 'magento:begin' "$tmp/b/CLAUDE.md")" "1" "C one begin marker"
assert_eq "$(grep -c 'magento:end' "$tmp/b/CLAUDE.md")" "1" "C one end marker"
assert_contains "$tmp/b/CLAUDE.md" "edition: commerce" "C new content present"
assert_not_contains "$tmp/b/CLAUDE.md" "edition: open-source" "C old content gone"
assert_contains "$tmp/b/CLAUDE.md" "^Trailing note.$" "C trailing text preserved"
assert_contains "$tmp/c.out" "^.claude/rules/magento.md: updated$" "C rules updated"
assert_contains "$tmp/b/.claude/rules/magento.md" "Rules v2" "C rules content"

# D. user-owned rules file is left alone
mkdir -p "$tmp/d/.claude/rules"; printf '# Mine\n' > "$tmp/d/.claude/rules/magento.md"
bash "$S" --block "$tmp/block1" --rules "$tmp/rules1" --root "$tmp/d" > "$tmp/d.out"
assert_contains "$tmp/d.out" "left alone \(owned by you\)" "D rules left alone"
assert_eq "$(cat "$tmp/d/.claude/rules/magento.md")" "# Mine" "D rules untouched"

# E. bad args
bash "$S" --block "$tmp/block1" > /dev/null 2>&1; assert_eq "$?" "1" "E usage exit"

report
