#!/usr/bin/env bash
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
S="$ROOT/plugins/magento/scripts/apply-init.sh"
tmp=$(mktemp -d)
printf '<!-- magento:begin -->\n## Magento (v1)\n- edition: open-source\n<!-- magento:end -->\n' > "$tmp/block1"
printf '<!-- magento:begin -->\n## Magento (v2)\n- edition: commerce\n<!-- magento:end -->\n' > "$tmp/block2"
printf '<!-- generated by the magento plugin v0.1.0 — remove this line to take ownership; init will then leave this file alone -->\n# Rules v1\n' > "$tmp/rules1"
printf '<!-- generated by the magento plugin v0.1.0 — remove this line to take ownership; init will then leave this file alone -->\n# Rules v2\n' > "$tmp/rules2"

# A. fresh project: creates both
mkdir "$tmp/a"
bash "$S" --block "$tmp/block1" --rules "$tmp/rules1" --root "$tmp/a" > "$tmp/a.out"
assert_contains "$tmp/a.out" "^CLAUDE.md: created$" "A claude created"
assert_contains "$tmp/a.out" "^.claude/rules/magento.md: created$" "A rules created"
assert_eq "$(grep -c 'magento:begin' "$tmp/a/CLAUDE.md")" "1" "A one begin marker"
assert_contains "$tmp/a/.claude/rules/magento.md" "Rules v1" "A rules content"

# B. existing CLAUDE.md without markers: appends, keeps existing text
mkdir "$tmp/b"; printf '# My project\n\nKeep me.\n' > "$tmp/b/CLAUDE.md"
bash "$S" --block "$tmp/block1" --rules "$tmp/rules1" --root "$tmp/b" > "$tmp/b.out"
assert_contains "$tmp/b.out" "^CLAUDE.md: appended$" "B appended"
assert_contains "$tmp/b/CLAUDE.md" "^Keep me.$" "B kept text"
assert_eq "$(head -1 "$tmp/b/CLAUDE.md")" "# My project" "B original first line intact"
assert_eq "$(grep -c 'magento:begin' "$tmp/b/CLAUDE.md")" "1" "B one begin marker"

# C. run again with a new block: replaces, still one block, text after block preserved
printf '\nTrailing note.\n' >> "$tmp/b/CLAUDE.md"
bash "$S" --block "$tmp/block2" --rules "$tmp/rules2" --root "$tmp/b" > "$tmp/c.out"
assert_contains "$tmp/c.out" "^CLAUDE.md: updated$" "C updated"
assert_eq "$(grep -c 'magento:begin' "$tmp/b/CLAUDE.md")" "1" "C one begin marker"
assert_eq "$(grep -c 'magento:end' "$tmp/b/CLAUDE.md")" "1" "C one end marker"
assert_contains "$tmp/b/CLAUDE.md" "edition: commerce" "C new content present"
assert_not_contains "$tmp/b/CLAUDE.md" "edition: open-source" "C old content gone"
assert_contains "$tmp/b/CLAUDE.md" "^Trailing note.$" "C trailing text preserved"
assert_contains "$tmp/c.out" "^.claude/rules/magento.md: updated$" "C rules updated"
assert_contains "$tmp/b/.claude/rules/magento.md" "Rules v2" "C rules content"

# D. user-owned rules file is left alone
mkdir -p "$tmp/d/.claude/rules"; printf '# Mine\n' > "$tmp/d/.claude/rules/magento.md"
bash "$S" --block "$tmp/block1" --rules "$tmp/rules1" --root "$tmp/d" > "$tmp/d.out"
assert_contains "$tmp/d.out" "left alone \(owned by you\)" "D rules left alone"
assert_eq "$(cat "$tmp/d/.claude/rules/magento.md")" "# Mine" "D rules untouched"

# E. bad args
bash "$S" --block "$tmp/block1" > /dev/null 2>&1; assert_eq "$?" "1" "E usage exit"

# F. marker text inside a fenced code example is not treated as the live block
mkdir "$tmp/f"
printf '# Heading\n\n```\n<!-- magento:begin -->\nexample\n<!-- magento:end -->\n```\n\n<!-- magento:begin -->\n## Magento (v1)\n- edition: open-source\n<!-- magento:end -->\n' > "$tmp/f/CLAUDE.md"
bash "$S" --block "$tmp/block2" --rules "$tmp/rules1" --root "$tmp/f" > "$tmp/f.out"
assert_contains "$tmp/f.out" "^CLAUDE.md: updated$" "F updated"
assert_contains "$tmp/f/CLAUDE.md" "^example$" "F fenced example unchanged"
assert_contains "$tmp/f/CLAUDE.md" "edition: commerce" "F new content present"
assert_not_contains "$tmp/f/CLAUDE.md" "edition: open-source" "F old content gone"
assert_eq "$(grep -c 'magento:begin' "$tmp/f/CLAUDE.md")" "2" "F two begin markers (fenced + live)"

# G. a write failure is reported and exits non-zero, not silently swallowed
mkdir -p "$tmp/g"
printf '<!-- magento:begin -->\n## Magento (v1)\n- edition: open-source\n<!-- magento:end -->\n' > "$tmp/g/CLAUDE.md"
if [ "$(id -u)" != "0" ]; then
  chmod 555 "$tmp/g"
  bash "$S" --block "$tmp/block2" --rules "$tmp/rules1" --root "$tmp/g" > "$tmp/g.out" 2>"$tmp/g.err"
  g_exit=$?
  chmod 755 "$tmp/g"
  assert_eq "$g_exit" "1" "G exit nonzero"
  assert_not_contains "$tmp/g.out" "^CLAUDE.md: updated$" "G stdout no updated"
  assert_contains "$tmp/g/CLAUDE.md" "edition: open-source" "G CLAUDE.md unchanged"
else
  echo "  SKIP: G write failure test (running as root)"
fi

# H. --block with no value falls through to usage, not an unbound-variable crash
bash "$S" --block > "$tmp/h.out" 2>"$tmp/h.err"; assert_eq "$?" "1" "H usage exit"
assert_contains "$tmp/h.err" "usage:" "H stderr usage"

# I. markers that exist ONLY inside a fence (no live block) must APPEND, not update
mkdir "$tmp/i"
printf '# Heading\n\n```\n<!-- magento:begin -->\nexample\n<!-- magento:end -->\n```\n\nMore text.\n' > "$tmp/i/CLAUDE.md"
bash "$S" --block "$tmp/block1" --rules "$tmp/rules1" --root "$tmp/i" > "$tmp/i.out"
assert_contains "$tmp/i.out" "^CLAUDE.md: appended$" "I appended (fence-only markers)"
assert_contains "$tmp/i/CLAUDE.md" "edition: open-source" "I new block present"
assert_contains "$tmp/i/CLAUDE.md" "^example$" "I fenced example still present"
assert_eq "$(grep -c 'magento:begin' "$tmp/i/CLAUDE.md")" "2" "I two begin markers (fenced + appended)"
assert_contains "$tmp/i/CLAUDE.md" "^More text.$" "I trailing text preserved"

# J. END marker before BEGIN (no closing END): not a live block — must not "update" (which would swallow
#    everything after the stray BEGIN); append instead and lose no original line
mkdir "$tmp/j"
printf '<!-- magento:end -->\nStray text between the markers.\n<!-- magento:begin -->\nText after the stray begin.\n' > "$tmp/j/CLAUDE.md"
bash "$S" --block "$tmp/block1" --rules "$tmp/rules1" --root "$tmp/j" > "$tmp/j.out" 2>&1; rc=$?
assert_not_contains "$tmp/j.out" "^CLAUDE.md: updated$" "J END-before-BEGIN is not treated as a live block"
if [ "$rc" -eq 0 ]; then assert_contains "$tmp/j.out" "^CLAUDE.md: appended$" "J appended"; else assert_contains "$tmp/j.out" "CLAUDE.md" "J non-zero exit names CLAUDE.md"; fi
assert_contains "$tmp/j/CLAUDE.md" "^Stray text between the markers.$" "J text between stray markers preserved"
assert_contains "$tmp/j/CLAUDE.md" "^Text after the stray begin.$" "J text after stray begin preserved"
assert_eq "$(grep -c '^<!-- magento:end -->$' "$tmp/j/CLAUDE.md")" "2" "J stray END kept plus appended END"

report
