#!/usr/bin/env bash
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
S="$ROOT/plugins/magento/scripts/render-rules.sh"
tmp=$(mktemp -d)

bash "$S" --version 0.1.0 --hyva false --luma true > "$tmp/luma.md"
assert_eq "$(head -1 "$tmp/luma.md")" "<!-- generated by the magento plugin v0.1.0 — remove this line to take ownership; init will then leave this file alone -->" "header line"
assert_not_contains "$tmp/luma.md" "^---$" "frontmatter stripped"
assert_not_contains "$tmp/luma.md" "^name: conventions" "frontmatter name stripped"
assert_contains "$tmp/luma.md" "^## Architecture" "architecture kept"
assert_contains "$tmp/luma.md" "^- \*\*A1\.\*\*" "A1 present"
assert_contains "$tmp/luma.md" "^## Frontend — Luma" "luma kept"
assert_not_contains "$tmp/luma.md" "^## Frontend — Hyvä" "hyva dropped"
assert_not_contains "$tmp/luma.md" "^- \*\*H1\.\*\*" "H1 dropped"
assert_not_contains "$tmp/luma.md" "^## How this file is used" "usage section dropped"
assert_contains "$tmp/luma.md" "^## Quality" "quality kept (section after dropped one)"

bash "$S" --version 0.1.0 --hyva true --luma false > "$tmp/hyva.md"
assert_contains "$tmp/hyva.md" "^## Frontend — Hyvä" "hyva kept"
assert_not_contains "$tmp/hyva.md" "^## Frontend — Luma" "luma dropped"
assert_not_contains "$tmp/hyva.md" "^- \*\*L1\.\*\*" "L1 dropped"

bash "$S" --version 0.1.0 > "$tmp/both.md"
assert_contains "$tmp/both.md" "^## Frontend — Luma" "default keeps luma"
assert_contains "$tmp/both.md" "^## Frontend — Hyvä" "default keeps hyva"

bash "$S" > /dev/null 2>&1; assert_eq "$?" "1" "missing --version exits 1"
report
